spring.application.name=CloudStorage

#Spring
spring.datasource.url=jdbc:postgresql://postgres:5432/postgres
spring.datasource.username=rama
spring.datasource.password=1122

#Redis
spring.data.redis.host=redis
spring.data.redis.port=6379
spring.data.redis.password=1122
spring.session.redis.repository-type=indexed
spring.session.redis.namespace=cloudstorage:session
spring.session.timeout=60m

#Hibernate
spring.jpa.hibernate.ddl-auto=validate

spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.jdbc.batch_versioned_data=true

#Hikari
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=20
spring.datasource.hikari.connection-timeout=10000

#Minio
app.minio.endpoint=http://minio:9000
app.minio.publicEndpoint=http://localhost:9000
app.minio.accessKey=rama
app.minio.secretKey=11223344
app.minio.bucketName=user-files

#Liquibase
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=true

#ResourceGarbageCollectorJob
app.cleanup.uploading.delay=PT1H
app.cleanup.deleting.delay=PT30M

#Logback
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level [%X{userId}] : %msg%n
